package br.com.rpires.dao.generic.jdbc;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class SchemaLoader {

    public static void criarSchema(Connection conn) throws SQLException {
        try (Statement stmt = conn.createStatement()) {

            // Tabela Cliente
            String sqlCliente = """
                CREATE TABLE IF NOT EXISTS TB_CLIENTE (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    NOME VARCHAR(100),
                    CPF BIGINT UNIQUE NOT NULL,
                    TEL BIGINT,
                    ENDERECO VARCHAR(100),
                    NUMERO INT,
                    CIDADE VARCHAR(50),
                    ESTADO VARCHAR(50),
                    EMAIL VARCHAR(100),
                    DATA_NASCIMENTO DATE
                );
            """;
            stmt.execute(sqlCliente);

            // Sequência Cliente
            String sqlSeqCliente = """
                CREATE SEQUENCE IF NOT EXISTS SQ_CLIENTE
                START WITH 1
                INCREMENT BY 1;
            """;
            stmt.execute(sqlSeqCliente);

            // Tabela Produto (com novo campo MARCA)
            String sqlProduto = """
                CREATE TABLE IF NOT EXISTS TB_PRODUTO (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    CODIGO VARCHAR(50) UNIQUE NOT NULL,
                    NOME VARCHAR(100),
                    DESCRICAO VARCHAR(255),
                    VALOR DECIMAL(10,2),
                    CATEGORIA VARCHAR(50),
                    MARCA VARCHAR(50)
                );
            """;
            stmt.execute(sqlProduto);

            // Sequência Produto
            String sqlSeqProduto = """
                CREATE SEQUENCE IF NOT EXISTS SQ_PRODUTO
                START WITH 1
                INCREMENT BY 1;
            """;
            stmt.execute(sqlSeqProduto);

        }
    }
}
